### ISSUE TITLE
Custom colors not working

### ISSUE THREAD

**Issue by Bluskript** [windicss/windicss-intellisense#33] opened 2021-03-01 22:03 UTC
I have the following config:
```ts
import { defineConfig } from 'vite-plugin-windicss'
import colors from 'windicss/colors'
import typography from 'windicss/plugin/typography'

export default defineConfig({
  darkMode: 'class',
  plugins: [
    typography(),
  ],
  theme: {
    extend: {
      colors: {
        primary: colors.blue,
        secondary: colors.amber,
        harmonydark: {
          50: '#f4f4f5',
          100: '#e9e9eb',
          200: '#c7c7cc',
          300: '#a5a5ad',
          400: '#626270',
          500: '#1f1e33',
          600: '#1c1b2e',
          700: '#171726',
          800: '#13121f',
          900: '#0f0f19',
        },
      },
    },
  },
})
```
However, autocomplete does not work for harmonydark, primary, or secondary.

**Comment by alexanderniebuhr** [comment] 2021-03-02 07:41
@Bluskript cannot reproduce

**Comment by Bluskript** [comment] 2021-03-02 07:44
Could you try reproducing this in a new project setup with the Vitesse template? My project is based on that.

**Comment by alexanderniebuhr** [comment] 2021-03-02 07:49
can you share your project, then i can test? setting up projects is out of scope for us

**Comment by voorjaar** [comment] 2021-03-02 07:51
oh. I think this issue caused by `windi/tailwind.config.ts`, current typescript config not support yet.

**Comment by alexanderniebuhr** [comment] 2021-03-02 07:53
@voorjaar also it is that in your config u are using` import / export `and not `require / module.exports` I am looking for the issue we had about this

**Comment by alexanderniebuhr** [comment] 2021-03-02 07:55
@Bluescript https://github.com/windicss/windicss-intellisense/issues/24

**Closed** 2021-03-02 21:46 UTC
Labels: invalid
