### ISSUE TITLE
Color preview not working in .tsx

### ISSUE THREAD

**Issue by gunters63** [windicss/windicss-intellisense#24] opened 2021-02-28 09:41 UTC
Hi,

Thanks for the quick bugfix of issue [22](https://github.com/windicss/windicss-intellisense/issues/22).

I tried version 0.0.6 now. The hover now only shows the preview once and the color preview now works in html files.

![image](https://user-images.githubusercontent.com/90346/109414119-c257c080-79e3-11eb-92b5-b14808b4936f.png)

But it is still not working in .tsx files.

![image](https://user-images.githubusercontent.com/90346/109414111-bbc94900-79e3-11eb-8524-2e0a96c12892.png)

Did I forget some configuration?

**Comment by gunters63** [comment] 2021-02-28 09:48
The sort utility also does not seem to work with .tsx files
Is color preview and sorting supposed to work with .tsx files?

**Comment by alexanderniebuhr** [comment] 2021-02-28 09:51
The issue is that we have not defined .tsx files in our file types... Do you know the vscode extension identifier for .tsx files? Then I can add them

```typescript
...
export const fileTypes: {
  extension: string;
  patterns: {
    regex: RegExp;
    splitCharacter: string;
  }[];
}[] = [
  {
    extension: 'javascript',
    patterns: jsPatterns,
  },
  {
    extension: 'javascriptreact',
    patterns: jsPatterns,
  },
  {
    extension: 'typescriptreact',
    patterns: jsPatterns,
  },
  {
    extension: 'html',
    patterns: htmlPatterns.concat( stylesPatterns),
  },
  {
    extension: 'php',
    patterns: htmlPatterns,
  },
  {
    extension: 'vue',
    patterns: htmlPatterns.concat( stylesPatterns),
  },
  {
    extension: 'svelte',
    patterns: htmlPatterns.concat( stylesPatterns),
  },
];
```

**Comment by alexanderniebuhr** [comment] 2021-02-28 09:56
actually, I cannot reproduce it. It works fine for me with an `.tsx` file. Can you provide me your file?

**Comment by gunters63** [comment] 2021-02-28 10:05
I looked into the sources and noticed that the extension tries to read `('**/{tailwind,windi}.config.js'`

 I am using windicss together with vite through the plugin [vite-plugin-windicss](https://github.com/windicss/vite-plugin-windicss). This makes it possible to rename the tailwind config file to tailwind.config.ts. Which is what I did.

Interestingly, when I rename my  tailwind.config.ts to tailwind.config.js (i don't use TS language features, but its nice to see intellisense on hover), the hover and color preview stops working completely, even for html files.

Here is my tailwind.config.ts:

````
import { defineConfig } from 'vite-plugin-windicss';
import colors from 'windicss/colors';
import forms from 'windicss/plugin/forms';
import typography from 'windicss/plugin/typography';

const theme = {
  state: {
    actual: colors.blue,
    alarm: colors.red,
    error: colors.red,
    heating: colors.amber,
    ok: colors.green,
    warning: colors.amber,
    inactive: colors.warmGray,
  },
  bg: {
    std: '#4c4c4c',
    panel: '#353535',
    'panel-error': '#7f1d1d',
    field: '#2a2a2a',
    readonly: '',
    input: '',
  },
  fg: {
    std: colors.coolGray[50],
  },
};

export default defineConfig({
  darkMode: 'class',
  shortcuts: {
    btn: 'rounded border border-gray-300 text-gray-600 px-4 py-2 m-2 inline-block hover:shadow',
  },
  theme: {
    extend: {
      colors: {
        fg: theme.fg.std,
        bg: theme.bg.std,
        panel: theme.bg.panel,
        field: theme.bg.field,
        ok: theme.state.ok,
        actual: theme.state.actual,
        alarm: theme.state.alarm,
        inactive: theme.state.inactive,
        heating: theme.state.heating,
        warning: theme.state.warning,
        warmGray: colors.warmGray,
        'enso-blue': '#8CA0B8',
      },
    },
  },
  plugins: [typography, forms],
});
````

Notice also defineConfig is used from vite-plugin-windicss.

**Comment by alexanderniebuhr** [comment] 2021-02-28 10:18
i just changed from module syntax to old syntax, then it works. Stil do not see a bug here. Have you setup your project for module-based logic correctly? for me fine.

```js
const { defineConfig } = require('vite-plugin-windicss')
const colors  = require('windicss/colors');
const forms = require('windicss/plugin/forms');
const typography = require('windicss/plugin/typography');

const theme = {
  state: {
    actual: colors.blue,
    alarm: colors.red,
    error: colors.red,
    heating: colors.amber,
    ok: colors.green,
    warning: colors.amber,
    inactive: colors.warmGray,
  },
  bg: {
    std: '#4c4c4c',
    panel: '#353535',
    'panel-error': '#7f1d1d',
    field: '#2a2a2a',
    readonly: '',
    input: '',
  },
  fg: {
    std: colors.coolGray[50],
  },
};

module.exports = defineConfig({
  darkMode: 'class',
  shortcuts: {
    btn: 'rounded border border-gray-300 text-gray-600 px-4 py-2 m-2 inline-block hover:shadow',
  },
  theme: {
    extend: {
      colors: {
        fg: theme.fg.std,
        bg: theme.bg.std,
        panel: theme.bg.panel,
        field: theme.bg.field,
        ok: theme.state.ok,
        actual: theme.state.actual,
        alarm: theme.state.alarm,
        inactive: theme.state.inactive,
        heating: theme.state.heating,
        warning: theme.state.warning,
        warmGray: colors.warmGray,
        'enso-blue': '#8CA0B8',
      },
    },
  },
  plugins: [typography, forms],
});
```

**Comment by gunters63** [comment] 2021-02-28 10:27
I did the same meanwhile :). color preview started working again in html, but not in .tsx.

I will try to create a small example project and upload it to Github

**Comment by alexanderniebuhr** [comment] 2021-02-28 10:29
just copy your `.tsx` please. Should be plenty to tell you why it is not working. Also it might be a cursor matching bug

**Comment by gunters63** [comment] 2021-02-28 10:30
Here it is:

````
import * as React from 'react';

export type LabelProps = { label?: string };

const Label = ({ label }: LabelProps): React.ReactElement => {
  return <label className="bg-rose-300 w-24 text-xs text-right">{label}</label>;
};

export default Label;
````

**Comment by alexanderniebuhr** [comment] 2021-02-28 10:38
will be fixed with release later tonight...

**Closed** 2021-02-28 10:37 UTC
Labels: question

**Comment by gunters63** [comment] 2021-02-28 10:45
Nice :). That should also fix it for jsx-Files and the not working class sorting.

**Comment by alexanderniebuhr** [comment] 2021-02-28 10:56
hopefully otherwise you can test later, and submit new issue

**Comment by gunters63** [comment] 2021-03-01 03:22
Thanks, .tsx files work fine now. .jsx file too it seems :)
