### ISSUE TITLE
Wrong suggestions with ctrl+space

### ISSUE THREAD

**Issue by itpropro** [windicss/windicss-intellisense#55] opened 2021-03-18 17:16 UTC
When trying to autocomplete something after a dash with ctrl+space, autocomplete doesn't consider the first part of the class:
![windicss_vscode](https://user-images.githubusercontent.com/15030951/111668327-eefa3d80-8815-11eb-9e01-a9ceec39a689.gif)

**Comment by natasha1007** [comment] 2021-03-22 19:04
Здравствуйте всем огромное спасибо за советы .

**Comment by alexanderniebuhr** [comment] 2021-04-03 21:15
@itpropro do you have the behavior with latest version? cannot reproduce it with latest update

**Comment by ThaddeusJiang** [comment] 2021-04-04 04:15
I have reproduced it, 

![CleanShot 2021-04-04 at 13 10 43](https://user-images.githubusercontent.com/17308201/113498385-697dc980-9547-11eb-8dea-aac9d5cbec88.gif)

The expect behavior

![CleanShot 2021-04-04 at 13 14 38@2x](https://user-images.githubusercontent.com/17308201/113498416-b95c9080-9547-11eb-82dd-e95c88d44a85.jpg)

**Comment by alexanderniebuhr** [comment] 2021-04-04 06:23
i still cannot reproduce it.. what file type are you using? i would like to have reproduction instruction
@ThaddeusJiang I assign it to you, if you have any fix let me know, an make a PR.

https://user-images.githubusercontent.com/45965090/113500528-fbbda780-951e-11eb-965d-e2f524c6e06b.mp4

**Comment by ThaddeusJiang** [comment] 2021-04-04 06:27
@alexanderniebuhr ok

I am using `.js` file.

**Comment by alexanderniebuhr** [comment] 2021-04-04 06:29
just a wild guess. do you guys have tailwind extension installed parallel?

**Comment by alexanderniebuhr** [comment] 2021-04-04 06:33
> I am using `.js` file

can confirm now.. `js` files do not work.. seems an issue with template literals.. you might need to try jsx with return, to get it narrow down

**Comment by ThaddeusJiang** [comment] 2021-04-04 06:50
Test

- [ ] jsx file do not work
![image](https://user-images.githubusercontent.com/17308201/113500890-9a1c2e00-955c-11eb-84d6-50eb10384331.png)

- [ ] vue file do not work
![CleanShot 2021-04-04 at 15 48 04](https://user-images.githubusercontent.com/17308201/113500984-31818100-955d-11eb-8924-aa6a1fd16b79.jpg)

- [x] css work
![CleanShot 2021-04-04 at 15 46 08@2x](https://user-images.githubusercontent.com/17308201/113500939-e9625e80-955c-11eb-91e1-146e09aa55bf.jpg)

- [x] HTML work
![CleanShot 2021-04-04 at 15 49 17](https://user-images.githubusercontent.com/17308201/113501015-5c6bd500-955d-11eb-8e8a-77912652db2d.jpg)

**Comment by ThaddeusJiang** [comment] 2021-04-04 07:05
I made a completion extension, it provides `sole` and `con-sole`.
I reproduced the same behavior in `plaintext` file, so I think this is vscode bug, not ours.

![CleanShot 2021-04-04 at 15 56 55@2x](https://user-images.githubusercontent.com/17308201/113501278-cc2e8f80-955e-11eb-800b-b5a4b5337314.jpg)

**Comment by alexanderniebuhr** [comment] 2021-04-04 08:18
ok let's see and wait. strange that it does work for `.svelte` files.
upstream issue: https://github.com/microsoft/vscode/issues/120495

**Comment by alexanderniebuhr** [comment] 2021-04-04 08:20
@ThaddeusJiang actually it does work for vue files for me.. super strange might be a vscode setting

**Comment by ThaddeusJiang** [comment] 2021-04-25 03:30
@alexanderniebuhr 
If I set `"files.associations": { "*.vue": "html" },` in my vscode setting, the vue file will work too.

**Comment by itpropro** [comment] 2021-05-10 19:53
@alexanderniebuhr this only happens with the windicss intellisense extension. If I use exactly the same project with the tailwindcss intellisense extension, everything works as expected, so tehre has to be something specific to this extension.

**Comment by alexanderniebuhr** [comment] 2021-05-11 04:32
Maybe. Maybe not. I am not sure if the tailwind extensions uses the native VS Code completion triggers.
Also there might be some stuff in the upstream issue to help understand the difference. I won't have time soon, so if you want to help. An PR is welcomed!

**Comment by itpropro** [comment] 2021-05-13 18:02
Fair point, I have no experience in coding them, but I will look into that.

**Comment by voorjaar** [comment] 2021-05-19 15:43
try to add this config to vscode
```
"editor.quickSuggestions": {
  "strings": true
}
```

**Comment by voorjaar** [comment] 2021-05-19 15:43
@itpropro  @ThaddeusJiang

**Comment by natasha1007** [comment] 2021-05-20 04:08
Vsem privet.

**Comment by voorjaar** [comment] 2021-05-24 21:21
After repeating the test many times, I thought this bug has been fixed in the latest version. I will close this issue for now and you can open it if there are still problems.

**Closed by voorjaar** 2021-05-24 21:21 UTC
Labels: bug, p3-high, upstream
